"use strict";
//An action that is executed as a result of the protocol that is executed. For example send a message that
//is generated by the protocol. It allows the simulation to intercept these actions, log them, and give the user a
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProtocolAction = void 0;
//todo rename ProtocolAction to OverlayActions? This is the only thing to be tampered with?
class ProtocolAction {
    type = 'ProtocolAction';
    isDisrupted = false;
}
exports.ProtocolAction = ProtocolAction;
