export default class NetworkStatisticsAggregation {
    time: Date;
    nrOfActiveWatchersSum: number;
    nrOfConnectableNodesSum: number;
    nrOfActiveValidatorsSum: number;
    nrOfActiveFullValidatorsSum: number;
    nrOfActiveOrganizationsSum: number;
    transitiveQuorumSetSizeSum: number;
    hasQuorumIntersectionCount: number;
    hasTransitiveQuorumSetCount: number;
    topTierMin: number;
    topTierMax: number;
    topTierSum: number;
    topTierOrgsMin: number;
    topTierOrgsMax: number;
    topTierOrgsSum: number;
    minBlockingSetMin: number;
    minBlockingSetMax: number;
    minBlockingSetSum: number;
    minBlockingSetOrgsMin: number;
    minBlockingSetOrgsMax: number;
    minBlockingSetOrgsSum: number;
    minBlockingCountryOrgsMin: number;
    minBlockingSetCountryMax: number;
    minBlockingSetCountrySum: number;
    minBlockingSetISPMin: number;
    minBlockingSetISPMax: number;
    minBlockingSetISPSum: number;
    minBlockingSetFilteredMin: number;
    minBlockingSetFilteredMax: number;
    minBlockingSetFilteredSum: number;
    minBlockingSetOrgsFilteredMin: number;
    minBlockingSetOrgsFilteredMax: number;
    minBlockingSetOrgsFilteredSum: number;
    minBlockingSetCountryFilteredMin: number;
    minBlockingSetCountryFilteredMax: number;
    minBlockingSetCountryFilteredSum: number;
    minBlockingSetISPFilteredMin: number;
    minBlockingSetISPFilteredMax: number;
    minBlockingSetISPFilteredSum: number;
    minSplittingSetMin: number;
    minSplittingSetMax: number;
    minSplittingSetSum: number;
    minSplittingSetOrgsMin: number;
    minSplittingSetOrgsMax: number;
    minSplittingSetOrgsSum: number;
    minSplittingSetCountryMin: number;
    minSplittingSetCountryMax: number;
    minSplittingSetCountrySum: number;
    minSplittingSetISPMin: number;
    minSplittingSetISPMax: number;
    minSplittingSetISPSum: number;
    hasSymmetricTopTierCount: number;
    crawlCount: number;
    get nrOfActiveWatchersAverage(): number;
    get nrOfConnectableNodesAverage(): number;
    get nrOfActiveValidatorsAverage(): number;
    get nrOfActiveFullValidatorsAverage(): number;
    get nrOfActiveOrganizationsAverage(): number;
    get transitiveQuorumSetSizeAverage(): number;
    get hasTransitiveQuorumSetAverage(): number;
    get hasQuorumIntersectionAverage(): number;
    get hasSymmetricTopTierAverage(): number;
    get topTierAverage(): number;
    get topTierOrgsAverage(): number;
    get minBlockingSetAverage(): number;
    get minBlockingSetFilteredAverage(): number;
    get minBlockingSetOrgsAverage(): number;
    get minBlockingSetOrgsFilteredAverage(): number;
    get minBlockingSetCountryAverage(): number;
    get minBlockingSetCountryFilteredAverage(): number;
    get minBlockingSetISPAverage(): number;
    get minBlockingSetISPFilteredAverage(): number;
    get minSplittingSetAverage(): number;
    get minSplittingSetOrgsAverage(): number;
    get minSplittingSetCountryAverage(): number;
    get minSplittingSetISPAverage(): number;
    protected getAverage(value: number): number;
    static fromJSON(networkStats: string | Record<string, unknown>): NetworkStatisticsAggregation;
}
//# sourceMappingURL=network-statistics-aggregation.d.ts.map